-- User Management Tables for Admin Dashboard

-- Drop existing objects if they exist (ignore errors if they don't exist)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ADMIN_REGISTRATION_REQUESTS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ADMIN_ACCESS_GRANTED_USERS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ADMIN_REGISTRATION_REQUESTS_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ADMIN_ACCESS_GRANTED_USERS_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

-- Table: ADMIN_REGISTRATION_REQUESTS
-- Purpose: Store pending user access requests
CREATE TABLE ADMIN_REGISTRATION_REQUESTS (
    REQUEST_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMPLOYEE_ID VARCHAR2(20) NOT NULL UNIQUE,
    DEPARTMENT VARCHAR2(100),
    DESIGNATION VARCHAR2(100),
    EMAIL VARCHAR2(100),
    REQUEST_STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (REQUEST_STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
    REQUESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROCESSED_AT TIMESTAMP NULL,
    PROCESSED_BY VARCHAR2(100) NULL
);

-- Table: ADMIN_ACCESS_GRANTED_USERS
-- Purpose: Store users approved to access the dashboard
CREATE TABLE ADMIN_ACCESS_GRANTED_USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMPLOYEE_ID VARCHAR2(20) NOT NULL UNIQUE,
    DEPARTMENT VARCHAR2(100),
    DESIGNATION VARCHAR2(100),
    EMAIL VARCHAR2(100),
    ACCESS_GRANTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_BY VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for better performance
-- Note: EMPLOYEE_ID indexes are automatically created due to UNIQUE constraint
CREATE INDEX IDX_REG_REQUESTS_STATUS ON ADMIN_REGISTRATION_REQUESTS(REQUEST_STATUS);
CREATE INDEX IDX_ACCESS_GRANTED_ACTIVE ON ADMIN_ACCESS_GRANTED_USERS(IS_ACTIVE);

-- Sequence for request IDs (if needed for manual inserts)
CREATE SEQUENCE ADMIN_REGISTRATION_REQUESTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN_ACCESS_GRANTED_USERS_SEQ START WITH 1 INCREMENT BY 1;

-- Comments for documentation
COMMENT ON TABLE ADMIN_REGISTRATION_REQUESTS IS 'Stores pending user access requests for the admin dashboard';
COMMENT ON COLUMN ADMIN_REGISTRATION_REQUESTS.REQUEST_ID IS 'Unique identifier for each registration request';
COMMENT ON COLUMN ADMIN_REGISTRATION_REQUESTS.FULL_NAME IS 'Full name of the user requesting access';
COMMENT ON COLUMN ADMIN_REGISTRATION_REQUESTS.EMPLOYEE_ID IS 'Employee ID of the user (must be unique)';
COMMENT ON COLUMN ADMIN_REGISTRATION_REQUESTS.DEPARTMENT IS 'Department of the user';
COMMENT ON COLUMN ADMIN_REGISTRATION_REQUESTS.DESIGNATION IS 'Designation/Role of the user';
COMMENT ON COLUMN ADMIN_REGISTRATION_REQUESTS.EMAIL IS 'Email address of the user';
COMMENT ON COLUMN ADMIN_REGISTRATION_REQUESTS.REQUEST_STATUS IS 'Status of the request (PENDING, APPROVED, REJECTED)';
COMMENT ON COLUMN ADMIN_REGISTRATION_REQUESTS.REQUESTED_AT IS 'Timestamp when the request was submitted';
COMMENT ON COLUMN ADMIN_REGISTRATION_REQUESTS.PROCESSED_AT IS 'Timestamp when the request was processed';
COMMENT ON COLUMN ADMIN_REGISTRATION_REQUESTS.PROCESSED_BY IS 'User who processed the request';

COMMENT ON TABLE ADMIN_ACCESS_GRANTED_USERS IS 'Stores users who have been granted access to the admin dashboard';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.USER_ID IS 'Unique identifier for each granted user';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.FULL_NAME IS 'Full name of the user';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.EMPLOYEE_ID IS 'Employee ID of the user (must be unique)';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.DEPARTMENT IS 'Department of the user';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.DESIGNATION IS 'Designation/Role of the user';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.EMAIL IS 'Email address of the user';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.ACCESS_GRANTED_AT IS 'Timestamp when access was granted';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.IS_ACTIVE IS 'Flag indicating if the user account is active (Y/N)';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.CREATED_BY IS 'User who granted the access';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.CREATED_AT IS 'Timestamp when the record was created';
COMMENT ON COLUMN ADMIN_ACCESS_GRANTED_USERS.UPDATED_AT IS 'Timestamp when the record was last updated';